# Generated by Django 6.0.8 on 2026-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='channel_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('email', 'Email')], max_length=20),
        ),
    ]
